### ISSUE TITLE
Sending File with import < operator fails

### ISSUE THREAD

**Issue by zatkhahi** [httpyac/httpyac.github.io#13] opened 2021-11-23 14:06 UTC
I am using httpyac vscode extension and wrote this .http file:

`
POST {{server}}/api/Formats/ImportFiles
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="ProjectId"

81
--WebKitFormBoundary
Content-Disposition: form-data; name="Format"

fgs
--WebKitFormBoundary
Content-Disposition: form-data; name="Files"; filename="pipes.shp"

< ./sample/pipes.shp
--WebKitFormBoundary
Content-Disposition: form-data; name="Files"; filename="pipes.dbf"

< ./sample/pipes.dbf
--WebKitFormBoundary--

`
This http file works when I use "Rest Client" extension but does not work with httpyac extension send. 
The problem is binary data importing with < operator is probably changing the data encoding or something else which the server cannot read the shp file.

**Comment by AnWeber** [comment] 2021-11-23 15:25
Can you give me a more specific hint as to what is going wrong here. I am successfully submitting PDF files using this function. Are both files binary or is one of them also text where the encoding becomes interesting. 
Actually the content of the file is passed directly to Got as a [buffer](https://github.com/AnWeber/httpyac/blob/main/src/actions/createReqeustBodyInterceptor.ts#L59-L90) and the encoding is not important. Exception is when explicitly reading is desired with (`<@`, meta data `# @injectVariables`  or setting `requestBodyInjectVariablesExtensions`).

**Comment by zatkhahi** [comment] 2021-11-24 05:03
I checked that exactly, it just prepend 2 more bytes to the sending file: 13 and 10  (in decimal byte)

**Comment by AnWeber** [comment] 2021-11-24 05:07
Thanks for finding out. That's a good hint. There is an unnecessary CRLF attached.

**Comment by AnWeber** [comment] 2021-11-25 21:30
I have found the cause. It is fixed in the next version. Thanks again for the hint with the bytes

**Comment by AnWeber** [comment] 2021-12-01 06:43
Fix I rolled out yesterday with the new version

**Closed by AnWeber** 2021-12-01 06:43 UTC
